### ISSUE TITLE
`max_col` appears to be ignored when set to 0

### ISSUE THREAD

**Issue by wkdavis** [tidyverts/feasts#150]
It looks like setting `max_col = 0` does not remove colors from `gg_season()` as per the documentation.

``` r
library(feasts)
#> Loading required package: fabletools
tsibbledata::aus_production %>% 
  gg_season(Cement, max_col = 0)
```

![](https://i.imgur.com/A29Nle6.png)

``` r
tsibbledata::aus_production %>% 
  gg_season(Cement, max_col = 0, labels = "none")
```

![](https://i.imgur.com/gbMctlw.png)

<sup>Created on 2022-05-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mitchelloharawild** [comment]
Thanks for reporting this. This argument was misdocumented after transitioning to a continuous default colour guide instead of showing now colours. I've restored its functionality as documented, but changed the default value to be `Inf` (since the continuous guide is a desirable default). A new argument `max_col_discrete` is added to control the threshold for discrete and continuous colour guides.

``` r
library(feasts)
#> Loading required package: fabletools
tsibbledata::aus_production %>% 
  gg_season(Cement, max_col = 0)
```

![](https://i.imgur.com/tc1hNof.png)

<sup>Created on 2022-08-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
