### ISSUE TITLE
function naming

### ISSUE THREAD

**Issue by earowang** [tidyverts/feasts#57]
https://github.com/tidyverts/feasts/blob/13aff9095b9369e1fcded4b5e45c4ac04514ef32/R/hctsa_features.R#L53

A large chunk of functions could be renamed to take advantage of autocompletions and suggesting similar functionalities. 

If `...` not used, can we remove it then?

**Comment by mitchelloharawild** [comment]
Only minor changes have been made from what is available in `tsfeatures`.
What naming convention do you suggest for these features?

`...` cannot be removed because the `summarise()` call will pass all inputs to all functions. It can be removed if `summarise()` is replaced with `map()`, however then no arguments could be passed via `...` (now that I think of it, passing inputs via `...` is likely a bad idea anyway.

**Comment by earowang** [comment]
Roughly:

* If a function returns multiple stats, use `features_*()`, for example `features_stl()`, `features_scaling()`, `features_prediction()`.
* If a function returns a single stat, use common prefix such as `acf_*()`, `entropy_*()`.

**Comment by earowang** [comment]
Can you briefly update `_pkgdown.yml` to split functions into sections? It'd be easier to see the common patterns for function name.

**Comment by earowang** [comment]
A shortcut for computing all features available in the package: `features_available()`

**Comment by mitchelloharawild** [comment]
Regarding `features_available()`, would it be better to use `features_feasts()`? That way `feasts.tsfresh` could use `features_tsfresh()`.

**Comment by earowang** [comment]
sounds good
